# example
dir:
  # work direcroty on local
  work: /tmp
  # backup directory under REDMINE_ROOT
  backup: [
    files,
    plugins,
    log
  ]
  remote: /tmp/redmine_back

ssh:
  host: localhost
  port: 2222
  user: vagrant
  password: vagrant
  passphrase:
  key: 
